INSTALL_TARGET_PROCESSES = SpringBoard
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = CanvasBackgroundSpringBoard

CanvasBackgroundSpringBoard_FILES = Tweak.x CBViewController.m
CanvasBackgroundSpringBoard_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk